#define END_OF_FILE 0
#define LEXICAL_ERROR -1

#define PROGRAM 2
#define IDENTIFIER 3
#define BEGINN 4
#define END 5
#define CONST 6
#define INTEGER 7
#define REAL 8
#define VAR 9
#define WHILE 10
#define DO 11
#define IF 12
#define ELSE 13
#define READ 14
#define WRITE 15
#define PROCEDURE 16
#define COLON 17
#define ATTRIBUTION 18
#define SEMICOLON 19
#define DOT 20
#define EQUAL 21
#define DIFFERENT 22
#define LESS_THAN_OR_EQUAL 23
#define GREATER_THAN_OR_EQUAL 24
#define GREATER_THAN 25
#define LESS_THAN 26
#define PAREN_LEFT 27
#define PAREN_RIGHT 28
#define FOR 29
#define TO 30
#define OP_AD 31
#define OP_MUL 32
#define COMMA 33
#define TYPE_INTEGER 34
#define TYPE_REAL 35